### ISSUE TITLE
Android Gradle Plugin 3.2.0 needs SDK Build Tools 28.0.3+

### ISSUE THREAD

**Issue by alexfdz** [CircleCI-Public/circleci-dockerfiles#13]
Currently the android images include the SDK Build Tools 28.0.0, but the 3.2.0 versions of the Android Gradle Plugin (latest stable) require 28.0.3 or higher.

https://developer.android.com/studio/releases/gradle-plugin#3-2-0

Would help build times if you can provide 28.0.3 by default.

**Comment by alexfdz** [comment]
Thanks @technoir42!

Do you know when it will be available to use in circleci-public/circleci-dockerfiles?

**Comment by iynere** [comment]
when we merge the staging branch of github.com/circleci/circleci-images into master @alexfdz

**Comment by juanimoli** [comment]
Hi @iynere,

We're having issues since this. Repositories with Gradle 3 are having issues with Robolectric. Some of the stacktrace is shown below:

```
test > testWithRobolectric FAILED
    java.lang.AssertionError: java.lang.IllegalAccessException: no such field: org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/699139716.__proxy__/android.content.res.Configuration/putField

        Caused by:
        java.lang.IllegalAccessException: no such field: org.robolectric.internal.bytecode.ProxyMaker$GeneratedProxy/699139716.__proxy__/android.content.res.Configuration/putField

            Caused by:
            java.lang.LinkageError: loader constraint violation: when resolving field "__proxy__" the class loader (instance of <bootloader>) of the referring class, org/robolectric/internal/bytecode/ProxyMaker$GeneratedProxy, and the class loader (instance of org/robolectric/internal/bytecode/SandboxClassLoader) for the field's resolved type, android/content/res/Configuration, have different Class objects for that type

test > anotherTest FAILED
    java.lang.NoClassDefFoundError: Could not initialize class android.content.res.Configuration
```

We want to know if the issue can be solved from the image, because we have changed the image to the latest success build's image, which works, or if the issue has to be solved from our side. No changes have been made in the version we use of Robolectric or our internal dependencies.

Thanks!

**Comment by iynere** [comment]
@juanimoli changes from staging that fixed this issue haven't been merged into master yet, will do that today

i haven't investigated your specific error, but if it's the same as the one the issue was created to address, then after the merge, the `circleci/android` images will have the requisite fix

**Comment by juanimoli** [comment]
@iynere allright, we will be waiting for the fix. Thanks!

**Comment by iynere** [comment]
great ! @juanimoli u can 👀 this job

https://circleci.com/gh/circleci/circleci-images/11519

when it finishes, the new images will be available

**Comment by juanimoli** [comment]
@iynere it didn't work :( is there anyway we can see this with more detail?

**Comment by iynere** [comment]
sorry, what didn't work ? @juanimoli if you're using the new images & still having this error, please feel free to open a support ticket : 

https://support.circleci.com/hc/en-us/requests/new

or, if you feel there's a separate issue with the images, please feel free to open a new one 🙏

**Comment by juanimoli** [comment]
@iynere will do that, thanks :D
